# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "crumble"
  s.version = "0.1.3"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Mathias Meyer"]
  s.date = "2012-02-27"
  s.description = "How did these breadcrumbs in your Rails application? Oh right, with this plugin!"
  s.email = "meyer@paperplanes.de"
  s.extra_rdoc_files = [
    "README.md"
  ]
  s.files = [
    "README.md",
    "Rakefile",
    "VERSION",
    "app/helpers/breadcrumbs_helper.rb",
    "lib/breadcrumb.rb",
    "lib/crumble/railtie.rb",
    "rails/init.rb",
    "spec/breadcrumb_spec.rb",
    "spec/breadcrumbs_helper_spec.rb",
    "spec/spec_helper.rb"
  ]
  s.homepage = "http://github.com/mattmatt/crumble"
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.10"
  s.summary = "Crumble - It's like breadcrumbs for your Rails application!"

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

